// <auto-generated />
using System;
using CocktailWizard.Data.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CocktailWizard.Data.Migrations
{
    [DbContext(typeof(CWContext))]
    [Migration("20191108221839_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CocktailWizard.Data.Entities.Ban", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("HasExpired");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasAlternateKey("CreatedOn", "Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bans");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.Bar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("GoogleMapsURL");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("CreatedOn", "Id");

                    b.ToTable("Bars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19fb565f-df92-4f81-ac42-bc256d10469a"),
                            Address = "1a Principal Place, Worship Street, London, EC2A 2BA",
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(7928),
                            GoogleMapsURL = "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d9930.13386419354!2d-0.0794724!3d51.5217746!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xfb717a4393ae1f7!2sThe%20Allegory!5e0!3m2!1sen!2sbg!4v1573065214726!5m2!1sen!2sbg",
                            ImagePath = "/assets/img/bars/the-allegory.jpg",
                            Info = "In the heart of Shoreditch's happening hub, Principal Place, The Allegory is an everyday escape in London’s buzzing unsquare mile. Linger over a long brunch before finishing with an espresso martini.Enjoy quick catch-ups over pastries and freshly ground coffee, wholesome sharing platters and creative cocktails with colleagues; these one-of-a-kind experiences will be found at The Allegory. With a beautiful alfresco terrace, large open plan bar and cosy candlelit corners, this is a destination you'll want to return to again and again.",
                            IsDeleted = false,
                            Name = "The Allegory",
                            Phone = "020 3948 9810"
                        },
                        new
                        {
                            Id = new Guid("49b52950-a806-4075-8260-9ba0bdc1ab06"),
                            Address = "1 Ropemaker Street, London, EC2Y 9HT",
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 206, DateTimeKind.Utc).AddTicks(836),
                            GoogleMapsURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d9931.461092179858!2d-0.12384975375194002!3d51.515687677335066!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487604af32e9d343%3A0x422a8e0b815341b!2sThe%20Refinery!5e0!3m2!1sen!2sbg!4v1573065262411!5m2!1sen!2sbg",
                            ImagePath = "/assets/img/bars/the-refinery.jpg",
                            Info = "Statement wallpapers and furniture are complemented by soft lighting and cosy faux fur to create your uber chic, contemporary bar - The Refinery CityPoint. The all-day dining bar & restaurant features a private dining room, sunken lounge and alfresco terrace with a pizza oven in the summer. It suits all occasions from early morning breakfasts right through to late night drinks. Make the most of our set menus for larger groups, or pre order packages when you want a selection of nibbles to eat!",
                            IsDeleted = false,
                            Name = "The Refinery",
                            Phone = "020 7382 0606"
                        },
                        new
                        {
                            Id = new Guid("6c296d75-bcd2-4711-9a28-6d0b6bcaa34b"),
                            Address = "52 Holborn Viaduct, London, EC1A 2FD",
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 206, DateTimeKind.Utc).AddTicks(867),
                            GoogleMapsURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2482.7646347568057!2d-0.1070710840279029!3d51.517533917782934!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48761b52ee3d7ad9%3A0xa677a8c2b71574ca!2sThe%20Fable!5e0!3m2!1sen!2sbg!4v1573065312782!5m2!1sen!2sbg",
                            ImagePath = "/assets/img/bars/the-fable.jpg",
                            Info = "Inspired by the fantasy world of fairy tales and Aesop's fables, The Fable near Holborn Viaduct in central London, is anything but ordinary. From the vintage typewriter, to the leather bound books, every detail tells a story. Whether you visit for crafted cocktails, a morning latte & eggs Benedict or dinner at dusk, expect to be entranced, enthralled and enchanted.",
                            IsDeleted = false,
                            Name = "The Fable",
                            Phone = "0207 651 4940"
                        },
                        new
                        {
                            Id = new Guid("4b6b8336-28df-48b2-a1fd-bade70b94eb6"),
                            Address = "Devonshire Terrace, Devonshire Square, London, EC2M 4WY",
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 206, DateTimeKind.Utc).AddTicks(874),
                            GoogleMapsURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2482.788117828657!2d-0.0803738840278907!3d51.517103117814386!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48761cb30d422641%3A0x2c7c1dfd5e33c70!2sDevonshire%20Terrace!5e0!3m2!1sen!2sbg!4v1573065339941!5m2!1sen!2sbg",
                            ImagePath = "/assets/img/bars/devonshire-terrace.jpg",
                            Info = "In the heart of the peaceful Devonshire Square, moments from Liverpool Street Station, Devonshire Terrace is your everyday escape from the hustle and bustle of City life. From quick catch-ups over freshly ground coffee to relaxing after work cocktails in one of our many gorgeous spaces, sit back and relax and we'll take care of the rest. No need to wait for the warmer months to drink and dine alfresco, enjoy our all year round terrace with its beautiful glass domed roof to protect you from the elements.",
                            IsDeleted = false,
                            Name = "Devonshire Terrace",
                            Phone = "020 7256 3233"
                        },
                        new
                        {
                            Id = new Guid("93532afb-fe74-43be-88a4-1c6948c634b8"),
                            Address = "58 Gresham Street, London, EC2V 7BB",
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 206, DateTimeKind.Utc).AddTicks(880),
                            GoogleMapsURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2482.788117828657!2d-0.0803738840278907!3d51.517103117814386!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487603552b6c7317%3A0x8e08163a80221ab9!2sThe%20Anthologist!5e0!3m2!1sen!2sbg!4v1573065358702!5m2!1sen!2sbg",
                            ImagePath = "/assets/img/bars/the-anthologist.jpg",
                            Info = "Located right in the heart of the City, The Anthologist is the ideal backdrop for all your drink and food needs, from breakfast meetings to client updates over lunch, after work drinks or dinner with friends. Sample new wines or vintages from across the globe, a unique range of innovative cocktails and relaxed all - day dining fare.",
                            IsDeleted = false,
                            Name = "The Anthologist",
                            Phone = "0207 726 8711"
                        },
                        new
                        {
                            Id = new Guid("64c6592d-2c7b-42c4-b18d-5ac34bdc39d1"),
                            Address = "6 Pancras Square, London, N1C 4AG",
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 206, DateTimeKind.Utc).AddTicks(885),
                            GoogleMapsURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2481.892053039409!2d-0.1282180840274676!3d51.53353971661222!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48761b3c54efa6e1%3A0x9f4c59afccfb8b53!2sDrake%20%26%20Morgan%20at%20King&#39;s%20Cross!5e0!3m2!1sen!2sbg!4v1573065385773!5m2!1sen!2sbg",
                            ImagePath = "/assets/img/bars/drakeandmorgan.jpg",
                            Info = "Our flagship bar & restaurant located in the heart of London's most exciting dining destination with two floors, two show stopping bars, an open kitchen and an extensive year-round outside space. Perfect for alfresco dining and drinks in the sun. Drake & Morgan at King's Cross offers a relaxed drinking and dining space in a beautiful setting. Open from an early morning until late evening, it's perfect for every occasion - from a business meeting and working lunch to a romantic dinner or after work drinks.",
                            IsDeleted = false,
                            Name = "Drake & Morgan",
                            Phone = "0203 826 4870"
                        },
                        new
                        {
                            Id = new Guid("84552d70-e670-4391-bd7b-1b54b0282b61"),
                            Address = "9 Cabot Square, London, E14 4EB",
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 206, DateTimeKind.Utc).AddTicks(891),
                            GoogleMapsURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2483.4112946113805!2d-0.025301484028207793!3d51.50566991865038!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487602b7be6a030f%3A0x93dcb32d47e3e562!2sThe%20Pagination!5e0!3m2!1sen!2sbg!4v1573065408325!5m2!1sen!2sbg",
                            ImagePath = "/assets/img/bars/the-pagination.jpg",
                            Info = "Perfectly positioned on the riverside in Canary Wharf, next to the bridge leading over to West India Quay, The Pagination is the perfect antidote to busy London life. With industrial inspired details, exposed metals, and soft handwoven textures, it offers a sanctuary, day or night and the expansive terrace offers alfresco drinking and dining in both the warmer months and the colder due to the abundance of blankets and hot water bottles to keep you snug.",
                            IsDeleted = false,
                            Name = "The Pagination",
                            Phone = "020 7512 0397"
                        },
                        new
                        {
                            Id = new Guid("69ce843b-97c4-4164-8ba0-c8ca4ef02cf4"),
                            Address = "The Park Pavilion, London, E14 5FW",
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 206, DateTimeKind.Utc).AddTicks(899),
                            GoogleMapsURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d39734.535778488505!2d-0.05813209602882269!3d51.50572144844429!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487602b7642f2f9d%3A0x19f521ba29dd3f1a!2sThe%20Parlour!5e0!3m2!1sen!2sbg!4v1573065440869!5m2!1sen!2sbg",
                            ImagePath = "/assets/img/bars/the-parlour.jpg",
                            Info = "Located in the Park Pavilion on Canada Square, Canary Wharf, The Parlour is a striking & innovative all-day bar with style, substance & seasonally tempting drinks and food. A secret garden-inspired lounge with timber panelling is a must for cocktail lovers & perfect for pre- or post-dinner drinks, whilst the mixology table is ideal for those who want to mix & muddle for themselves. A stunning alfresco terrace, complete with its own bar provides the perfect playpen for those wanting to soak up the sun.",
                            IsDeleted = false,
                            Name = "The Parlour",
                            Phone = "0207 715 9551"
                        },
                        new
                        {
                            Id = new Guid("363ea8fb-60f3-4aa2-8041-394520e3fb41"),
                            Address = "5-16 Gerrard Street, London, W1D 6JE",
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 206, DateTimeKind.Utc).AddTicks(905),
                            GoogleMapsURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2483.0790771431516!2d-0.13363628402805472!3d51.511765218204765!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487604d25acdb76d%3A0xc5c854eeaaa62990!2sOpium%20Cocktail%20bar%20and%20Dim%20Sum%20Parlour!5e0!3m2!1sen!2sbg!4v1573065470157!5m2!1sen!2sbg",
                            ImagePath = "/assets/img/bars/opium.jpg",
                            Info = "Opium Cocktail Bar & Dim Sum Parlour is a chic, hidden venue in the heart of Chinatown. Run by experienced London bar moguls Dre Masso and Eric Yu, Opium certainly has some pedigree behind it. The decor is oriental themed but again keeps an element of freshness with a twist that makes it modern and current; metal finishes on miss-matched Chinese furniture gives Opium, a contemporary London feel that is very welcome. Expect 3 bars of amazing Asian cocktails and a selection of dim sum - just a little teaser to get your appetite going.",
                            IsDeleted = false,
                            Name = "Opium",
                            Phone = "020 7734 7276"
                        },
                        new
                        {
                            Id = new Guid("11f5779b-49b1-43ac-9153-5fa72d810b34"),
                            Address = "16 Hertsmere Road, London, E14 4AX",
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 206, DateTimeKind.Utc).AddTicks(910),
                            GoogleMapsURL = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2483.3029276456064!2d-0.0260607840281346!3d51.5076582185051!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487602b6306f0be9%3A0x793dfd9d17079629!2sThe%20Sipping%20Room!5e0!3m2!1sen!2sbg!4v1573065491821!5m2!1sen!2sbg",
                            ImagePath = "/assets/img/bars/the-sipping-room.jpg",
                            Info = "An escape from the everyday, The Sipping Room specialises in thoughtful, inspired menus, locally sourced ingredients, and innovative, handcrafted cocktails. Retreat from the world while you enjoy our unrivalled service in the most welcoming environment. Our stylish outdoor terrace provides the perfect alfresco respite throughout the seasons.",
                            IsDeleted = false,
                            Name = "The Sipping Room",
                            Phone = "020 3907 0320"
                        });
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarCocktail", b =>
                {
                    b.Property<Guid>("CocktailId");

                    b.Property<Guid>("BarId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("CocktailId", "BarId");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("BarId");

                    b.ToTable("BarCocktails");

                    b.HasData(
                        new
                        {
                            CocktailId = new Guid("24e8a669-799a-48b7-bc6f-b6884a33d0c7"),
                            BarId = new Guid("19fb565f-df92-4f81-ac42-bc256d10469a"),
                            CreatedOn = new DateTime(2019, 11, 9, 0, 18, 39, 206, DateTimeKind.Local).AddTicks(2885),
                            IsDeleted = false
                        },
                        new
                        {
                            CocktailId = new Guid("e9b10c8b-46ed-45a3-9c66-a2c92d74e112"),
                            BarId = new Guid("19fb565f-df92-4f81-ac42-bc256d10469a"),
                            CreatedOn = new DateTime(2019, 11, 9, 0, 18, 39, 207, DateTimeKind.Local).AddTicks(3148),
                            IsDeleted = false
                        },
                        new
                        {
                            CocktailId = new Guid("3ebcd248-c91b-45e4-8900-90748828cc67"),
                            BarId = new Guid("19fb565f-df92-4f81-ac42-bc256d10469a"),
                            CreatedOn = new DateTime(2019, 11, 9, 0, 18, 39, 207, DateTimeKind.Local).AddTicks(3161),
                            IsDeleted = false
                        },
                        new
                        {
                            CocktailId = new Guid("c2acdffb-a172-4b52-9316-8a5bbe02c16d"),
                            BarId = new Guid("19fb565f-df92-4f81-ac42-bc256d10469a"),
                            CreatedOn = new DateTime(2019, 11, 9, 0, 18, 39, 207, DateTimeKind.Local).AddTicks(3164),
                            IsDeleted = false
                        },
                        new
                        {
                            CocktailId = new Guid("e9b10c8b-46ed-45a3-9c66-a2c92d74e112"),
                            BarId = new Guid("49b52950-a806-4075-8260-9ba0bdc1ab06"),
                            CreatedOn = new DateTime(2019, 11, 9, 0, 18, 39, 207, DateTimeKind.Local).AddTicks(3167),
                            IsDeleted = false
                        },
                        new
                        {
                            CocktailId = new Guid("b725576e-25cb-4d3e-b661-68e6df37e2f7"),
                            BarId = new Guid("49b52950-a806-4075-8260-9ba0bdc1ab06"),
                            CreatedOn = new DateTime(2019, 11, 9, 0, 18, 39, 207, DateTimeKind.Local).AddTicks(3170),
                            IsDeleted = false
                        },
                        new
                        {
                            CocktailId = new Guid("1dc069f0-0caa-4b64-82c0-66a744607ab1"),
                            BarId = new Guid("6c296d75-bcd2-4711-9a28-6d0b6bcaa34b"),
                            CreatedOn = new DateTime(2019, 11, 9, 0, 18, 39, 207, DateTimeKind.Local).AddTicks(3172),
                            IsDeleted = false
                        },
                        new
                        {
                            CocktailId = new Guid("2b113d19-305b-43f0-b149-44e86e7f8308"),
                            BarId = new Guid("6c296d75-bcd2-4711-9a28-6d0b6bcaa34b"),
                            CreatedOn = new DateTime(2019, 11, 9, 0, 18, 39, 207, DateTimeKind.Local).AddTicks(3174),
                            IsDeleted = false
                        },
                        new
                        {
                            CocktailId = new Guid("86a1c72c-4daf-4e26-a483-67b569b5271f"),
                            BarId = new Guid("6c296d75-bcd2-4711-9a28-6d0b6bcaa34b"),
                            CreatedOn = new DateTime(2019, 11, 9, 0, 18, 39, 207, DateTimeKind.Local).AddTicks(3177),
                            IsDeleted = false
                        },
                        new
                        {
                            CocktailId = new Guid("c2acdffb-a172-4b52-9316-8a5bbe02c16d"),
                            BarId = new Guid("4b6b8336-28df-48b2-a1fd-bade70b94eb6"),
                            CreatedOn = new DateTime(2019, 11, 9, 0, 18, 39, 207, DateTimeKind.Local).AddTicks(3179),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarComment", b =>
                {
                    b.Property<Guid>("BarId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("UserId");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("BarId", "UserId");

                    b.HasAlternateKey("BarId", "CreatedOn");

                    b.HasIndex("UserId");

                    b.ToTable("BarComments");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarRating", b =>
                {
                    b.Property<Guid>("BarId");

                    b.Property<Guid>("UserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("Value");

                    b.HasKey("BarId", "UserId");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("UserId");

                    b.ToTable("BarRatings");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.Cocktail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.HasAlternateKey("CreatedOn", "Id");

                    b.ToTable("Cocktails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24e8a669-799a-48b7-bc6f-b6884a33d0c7"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(4169),
                            ImagePath = "/assets/img/cocktails/cosmopolitan-cocktail.jpg",
                            Info = "Lipsmackingly sweet-and-sour, the Cosmopolitan cocktail of vodka, cranberry, orange liqueur and citrus is a good time in a glass. Perfect for a party.",
                            IsDeleted = false,
                            Name = "Cosmopolitan cocktail"
                        },
                        new
                        {
                            Id = new Guid("e9b10c8b-46ed-45a3-9c66-a2c92d74e112"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(6972),
                            ImagePath = "/assets/img/cocktails/passionfruit-martini.jpg",
                            Info = "This easy passion fruit cocktail is bursting with zingy flavours and is perfect for celebrating with friends. Top with prosecco for a special tipple",
                            IsDeleted = false,
                            Name = "Passion fruit martini"
                        },
                        new
                        {
                            Id = new Guid("3ebcd248-c91b-45e4-8900-90748828cc67"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(7002),
                            ImagePath = "/assets/img/cocktails/raspberry-gin.jpg",
                            Info = "Preserve the taste of summer in a bottle with this raspberry gin, perfect topped up with tonic. The gin will keep its lovely pink hue for a few months",
                            IsDeleted = false,
                            Name = "Raspberry gin"
                        },
                        new
                        {
                            Id = new Guid("c2acdffb-a172-4b52-9316-8a5bbe02c16d"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(7008),
                            ImagePath = "/assets/img/cocktails/sex-on-the-beach.jpg",
                            Info = "Combine vodka with peach schnapps and cranberry juice to make a classic sex on the beach cocktail. Garnish with cocktail cherries and orange slices.",
                            IsDeleted = false,
                            Name = "Sex on the beach cocktail"
                        },
                        new
                        {
                            Id = new Guid("1686f69d-baaf-4423-a857-4b4d1684496f"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(7014),
                            ImagePath = "/assets/img/cocktails/pink-gin-iced-tea.jpg",
                            Info = "Blend pink gin with iced tea and you have this unique cocktail, made with spiced rum, elderflower and pink grapefruit. Serve in a jug for a sharing cocktail.",
                            IsDeleted = false,
                            Name = "Pink gin iced tea"
                        },
                        new
                        {
                            Id = new Guid("1dc069f0-0caa-4b64-82c0-66a744607ab1"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(7019),
                            ImagePath = "/assets/img/cocktails/long-island-ice-tea.jpg",
                            Info = "Mix a jug of this classic cocktail for a summer party. It's made with equal parts of vodka, gin, tequila, rum and triple sec, plus lime, cola and plenty of ice.",
                            IsDeleted = false,
                            Name = "Long Island iced tea"
                        },
                        new
                        {
                            Id = new Guid("2b113d19-305b-43f0-b149-44e86e7f8308"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(7024),
                            ImagePath = "/assets/img/cocktails/michelada.jpg",
                            Info = "Cold lager, chilli powder, pepper and lime: spice up your lager with this Mexican cocktail, popular throughout Latin America and great for a summer party.",
                            IsDeleted = false,
                            Name = "Michelada"
                        },
                        new
                        {
                            Id = new Guid("323bc1dd-c842-4689-bc7b-2953787a3129"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(7029),
                            ImagePath = "/assets/img/cocktails/wine-sangria.jpg",
                            Info = "Try this refreshing twist on a traditional sangria and use white wine instead of red with elderflower to complement the fruit. Perfect for summer parties.",
                            IsDeleted = false,
                            Name = "White wine sangria"
                        },
                        new
                        {
                            Id = new Guid("b725576e-25cb-4d3e-b661-68e6df37e2f7"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(7034),
                            ImagePath = "/assets/img/cocktails/bucks-fizz.jpg",
                            Info = "The simple and classic combination of orange juice and champagne makes a perfect cocktail for a celebratory brunch or party",
                            IsDeleted = false,
                            Name = "Bucks fizz"
                        },
                        new
                        {
                            Id = new Guid("86a1c72c-4daf-4e26-a483-67b569b5271f"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(7040),
                            ImagePath = "/assets/img/cocktails/cranberry-vodka.jpg",
                            Info = "This bittersweet fruity vodka is best served well chilled in shot glasses. It can also be made with other berries like blackcurrants or strawberries.",
                            IsDeleted = false,
                            Name = "Cranberry vodka"
                        });
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailComment", b =>
                {
                    b.Property<Guid>("CocktailId");

                    b.Property<Guid>("UserId");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("CocktailId", "UserId");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("UserId");

                    b.ToTable("CocktailComments");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailIngredient", b =>
                {
                    b.Property<Guid>("IngredientId");

                    b.Property<Guid>("CocktailId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("IngredientId", "CocktailId");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("CocktailId");

                    b.ToTable("CocktailIngredient");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailRating", b =>
                {
                    b.Property<Guid>("CocktailId");

                    b.Property<Guid>("UserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("Value");

                    b.HasKey("CocktailId", "UserId");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("UserId");

                    b.ToTable("CocktailRatings");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasAlternateKey("CreatedOn", "Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("91767830-fb0e-4e77-a93a-d01eb2520553"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(1156),
                            IsDeleted = false,
                            Name = "Whisky"
                        },
                        new
                        {
                            Id = new Guid("af31c27c-d4e5-4d19-8304-2c649adb2f49"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2761),
                            IsDeleted = false,
                            Name = "Gin"
                        },
                        new
                        {
                            Id = new Guid("8b4157a7-49f0-4487-b800-c569c9ec7dd6"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2780),
                            IsDeleted = false,
                            Name = "Vodka"
                        },
                        new
                        {
                            Id = new Guid("f97a5f83-f9da-43a3-bef9-67091533ccc9"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2787),
                            IsDeleted = false,
                            Name = "Rum"
                        },
                        new
                        {
                            Id = new Guid("4f036905-92af-4b1b-8879-41b0fa8f1020"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2793),
                            IsDeleted = false,
                            Name = "Tequila"
                        },
                        new
                        {
                            Id = new Guid("0303b014-79b5-4044-9994-85ac83f293fc"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2797),
                            IsDeleted = false,
                            Name = "Cointreau"
                        },
                        new
                        {
                            Id = new Guid("730bcb1e-ed31-4600-9e42-7019898154b5"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2802),
                            IsDeleted = false,
                            Name = "Cola"
                        },
                        new
                        {
                            Id = new Guid("7f5402b0-2136-4abb-b809-86c1cb502f62"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2806),
                            IsDeleted = false,
                            Name = "Ginger ale"
                        },
                        new
                        {
                            Id = new Guid("f9d9ac89-7c03-4a41-8a1a-b69262f89e16"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2811),
                            IsDeleted = false,
                            Name = "Club soda"
                        },
                        new
                        {
                            Id = new Guid("dd3b4dcd-1e23-4b02-bdf1-859d892a7d89"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2816),
                            IsDeleted = false,
                            Name = "Lemon Sour"
                        },
                        new
                        {
                            Id = new Guid("59bd8032-57f2-4193-8d40-c805ec7d6122"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2819),
                            IsDeleted = false,
                            Name = "Cinnamon Syrup"
                        },
                        new
                        {
                            Id = new Guid("2d403bd0-6656-48a3-80a5-1910f2526d94"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2823),
                            IsDeleted = false,
                            Name = "Triple sec"
                        },
                        new
                        {
                            Id = new Guid("99667755-0b3c-4746-89da-9d8dd7a6169a"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2827),
                            IsDeleted = false,
                            Name = "Cranberry juice"
                        },
                        new
                        {
                            Id = new Guid("5998858c-01e8-41d2-8116-798649a2763f"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2831),
                            IsDeleted = false,
                            Name = "Lime wedge"
                        },
                        new
                        {
                            Id = new Guid("b988748e-cd6a-48da-aa36-20773102e426"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2835),
                            IsDeleted = false,
                            Name = "Passoa"
                        },
                        new
                        {
                            Id = new Guid("5495d66c-52ff-43f3-b26d-1b5279e07767"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2839),
                            IsDeleted = false,
                            Name = "Sugar syrup"
                        },
                        new
                        {
                            Id = new Guid("e05c419e-2f82-425c-b769-2842179d7e85"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2843),
                            IsDeleted = false,
                            Name = "Prosecco"
                        },
                        new
                        {
                            Id = new Guid("12b1f952-2e1f-4758-9e80-1c1efba96cc5"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2847),
                            IsDeleted = false,
                            Name = "Raspberries"
                        },
                        new
                        {
                            Id = new Guid("7982b0ce-b116-44dd-85a8-06e66df516cc"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2851),
                            IsDeleted = false,
                            Name = "Strawberries"
                        },
                        new
                        {
                            Id = new Guid("145fd313-ef00-4003-b95a-a5e6558f255d"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2856),
                            IsDeleted = false,
                            Name = "Peach schnapps"
                        },
                        new
                        {
                            Id = new Guid("47cac5ab-7071-46c9-bfbb-0f6ffaff0f0b"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2860),
                            IsDeleted = false,
                            Name = "Oranges"
                        },
                        new
                        {
                            Id = new Guid("30743785-290f-460c-b16e-6fc992b44366"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2865),
                            IsDeleted = false,
                            Name = "Cherries"
                        },
                        new
                        {
                            Id = new Guid("cce2c9a4-e14a-4cf9-83ad-111fa4a19eaf"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2869),
                            IsDeleted = false,
                            Name = "Olives"
                        },
                        new
                        {
                            Id = new Guid("2d5dd44c-41d7-43d0-9139-81aa791089a3"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2873),
                            IsDeleted = false,
                            Name = "Apples"
                        },
                        new
                        {
                            Id = new Guid("ad6430e6-0b4b-49aa-b412-7d6f6ddbe5b0"),
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 205, DateTimeKind.Utc).AddTicks(2877),
                            IsDeleted = false,
                            Name = "Kiwis"
                        });
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("297d06e6-c058-486f-a18a-06a971ebfcd7"),
                            ConcurrencyStamp = "6fdc2f0d-bfa7-49e4-85c0-8510457befed",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("6c8fcd7e-62f6-4f3e-a73d-acbfd60b97ab"),
                            ConcurrencyStamp = "88510f62-aacd-4603-9063-07ba02e128e5",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bd06fe6-79ca-43a1-862b-446a1466bb93"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0b9b9219-5b25-4fb1-ae81-c2c040854f82",
                            CreatedOn = new DateTime(2019, 11, 8, 22, 18, 39, 196, DateTimeKind.Utc).AddTicks(3980),
                            Email = "manager@cw.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "MANAGER@CW.COM",
                            NormalizedUserName = "MANAGER@CW.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEN48HFJ9oCf/2Dcqfkrfymj8V/zT7aszTPggpnBAj5aKCQUtf0cefmsTuq9E7MJ5ew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7I5VNHIJTSZNOT3KDWKNFUV5PVYBHGXN",
                            TwoFactorEnabled = false,
                            UserName = "manager@cw.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("7bd06fe6-79ca-43a1-862b-446a1466bb93"),
                            RoleId = new Guid("297d06e6-c058-486f-a18a-06a971ebfcd7")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.Ban", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.User", "User")
                        .WithMany("Bans")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarCocktail", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Bar", "Bar")
                        .WithMany("BarCocktails")
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CocktailWizard.Data.Entities.Cocktail", "Cocktail")
                        .WithMany("BarCocktails")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarComment", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Bar", "Bar")
                        .WithMany("Comments")
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.User", "User")
                        .WithMany("BarComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarRating", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Bar", "Bar")
                        .WithMany("Ratings")
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.User", "User")
                        .WithMany("BarRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailComment", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Cocktail", "Cocktail")
                        .WithMany("Comments")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.User", "User")
                        .WithMany("CocktailComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailIngredient", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Cocktail", "Cocktail")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailRating", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Cocktail", "Cocktail")
                        .WithMany("Ratings")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.User", "User")
                        .WithMany("CocktailRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
