// <auto-generated />
using System;
using CocktailWizard.Data.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CocktailWizard.Data.Migrations
{
    [DbContext(typeof(CWContext))]
    [Migration("20191103135413_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CocktailWizard.Data.Entities.Ban", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("HasExpired");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasAlternateKey("CreatedOn", "Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bans");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.Bar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("CreatedOn", "Id");

                    b.ToTable("Bars");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarCocktail", b =>
                {
                    b.Property<Guid>("CocktailId");

                    b.Property<Guid>("BarId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("CocktailId", "BarId");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("BarId");

                    b.ToTable("BarCocktails");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarComment", b =>
                {
                    b.Property<Guid>("BarId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("UserId");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("BarId", "UserId");

                    b.HasAlternateKey("BarId", "CreatedOn");

                    b.HasIndex("UserId");

                    b.ToTable("BarComments");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarRating", b =>
                {
                    b.Property<Guid>("BarId");

                    b.Property<Guid>("UserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("Value");

                    b.HasKey("BarId", "UserId");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("UserId");

                    b.ToTable("BarRatings");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.Cocktail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasAlternateKey("CreatedOn", "Id");

                    b.ToTable("Cocktails");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailComment", b =>
                {
                    b.Property<Guid>("CocktailId");

                    b.Property<Guid>("UserId");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("CocktailId", "UserId");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("UserId");

                    b.ToTable("CocktailComments");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailIngredient", b =>
                {
                    b.Property<Guid>("IngredientId");

                    b.Property<Guid>("CocktailId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("IngredientId", "CocktailId");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("CocktailId");

                    b.ToTable("CocktailIngredient");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailRating", b =>
                {
                    b.Property<Guid>("CocktailId");

                    b.Property<Guid>("UserId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<double>("Value");

                    b.HasKey("CocktailId", "UserId");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("UserId");

                    b.ToTable("CocktailRatings");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasAlternateKey("CreatedOn", "Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("91767830-fb0e-4e77-a93a-d01eb2520553"),
                            CreatedOn = new DateTime(2019, 11, 3, 13, 54, 13, 420, DateTimeKind.Utc).AddTicks(3849),
                            IsDeleted = false,
                            Name = "Whisky"
                        },
                        new
                        {
                            Id = new Guid("af31c27c-d4e5-4d19-8304-2c649adb2f49"),
                            CreatedOn = new DateTime(2019, 11, 3, 13, 54, 13, 420, DateTimeKind.Utc).AddTicks(5136),
                            IsDeleted = false,
                            Name = "Gin"
                        },
                        new
                        {
                            Id = new Guid("8b4157a7-49f0-4487-b800-c569c9ec7dd6"),
                            CreatedOn = new DateTime(2019, 11, 3, 13, 54, 13, 420, DateTimeKind.Utc).AddTicks(5153),
                            IsDeleted = false,
                            Name = "Vodka"
                        },
                        new
                        {
                            Id = new Guid("f97a5f83-f9da-43a3-bef9-67091533ccc9"),
                            CreatedOn = new DateTime(2019, 11, 3, 13, 54, 13, 420, DateTimeKind.Utc).AddTicks(5159),
                            IsDeleted = false,
                            Name = "Rum"
                        },
                        new
                        {
                            Id = new Guid("4f036905-92af-4b1b-8879-41b0fa8f1020"),
                            CreatedOn = new DateTime(2019, 11, 3, 13, 54, 13, 420, DateTimeKind.Utc).AddTicks(5165),
                            IsDeleted = false,
                            Name = "Tequila"
                        },
                        new
                        {
                            Id = new Guid("0303b014-79b5-4044-9994-85ac83f293fc"),
                            CreatedOn = new DateTime(2019, 11, 3, 13, 54, 13, 420, DateTimeKind.Utc).AddTicks(5169),
                            IsDeleted = false,
                            Name = "Cointreau"
                        },
                        new
                        {
                            Id = new Guid("730bcb1e-ed31-4600-9e42-7019898154b5"),
                            CreatedOn = new DateTime(2019, 11, 3, 13, 54, 13, 420, DateTimeKind.Utc).AddTicks(5174),
                            IsDeleted = false,
                            Name = "Cola"
                        },
                        new
                        {
                            Id = new Guid("7f5402b0-2136-4abb-b809-86c1cb502f62"),
                            CreatedOn = new DateTime(2019, 11, 3, 13, 54, 13, 420, DateTimeKind.Utc).AddTicks(5178),
                            IsDeleted = false,
                            Name = "Ginger Ale"
                        },
                        new
                        {
                            Id = new Guid("f9d9ac89-7c03-4a41-8a1a-b69262f89e16"),
                            CreatedOn = new DateTime(2019, 11, 3, 13, 54, 13, 420, DateTimeKind.Utc).AddTicks(5182),
                            IsDeleted = false,
                            Name = "Club Soda"
                        },
                        new
                        {
                            Id = new Guid("dd3b4dcd-1e23-4b02-bdf1-859d892a7d89"),
                            CreatedOn = new DateTime(2019, 11, 3, 13, 54, 13, 420, DateTimeKind.Utc).AddTicks(5186),
                            IsDeleted = false,
                            Name = "Lemon Sour"
                        });
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("297d06e6-c058-486f-a18a-06a971ebfcd7"),
                            ConcurrencyStamp = "650ae263-8958-413e-a8e8-f886a987e3d8",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("6c8fcd7e-62f6-4f3e-a73d-acbfd60b97ab"),
                            ConcurrencyStamp = "838873eb-cc36-472a-823e-efa1f35ff7d3",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasAlternateKey("CreatedOn");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7bd06fe6-79ca-43a1-862b-446a1466bb93"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05b07a8f-5de4-4f55-acc3-c542956a868c",
                            CreatedOn = new DateTime(2019, 11, 3, 13, 54, 13, 412, DateTimeKind.Utc).AddTicks(3325),
                            Email = "manager@cw.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "MANAGER@CW.COM",
                            NormalizedUserName = "MANAGER@CW.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOH9vTx73SxIktJZDiX3Q19dtZku0Fdt9ypJiyaoALfVl9lE0/Re7R4ZJ1M39hKyEQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7I5VNHIJTSZNOT3KDWKNFUV5PVYBHGXN",
                            TwoFactorEnabled = false,
                            UserName = "manager@cw.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<Guid>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("7bd06fe6-79ca-43a1-862b-446a1466bb93"),
                            RoleId = new Guid("297d06e6-c058-486f-a18a-06a971ebfcd7")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.Ban", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.User", "User")
                        .WithMany("Bans")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarCocktail", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Bar", "Bar")
                        .WithMany("BarCocktails")
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CocktailWizard.Data.Entities.Cocktail", "Cocktail")
                        .WithMany("BarCocktails")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarComment", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Bar", "Bar")
                        .WithMany("Comments")
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.User", "User")
                        .WithMany("BarComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.BarRating", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Bar", "Bar")
                        .WithMany("Ratings")
                        .HasForeignKey("BarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.User", "User")
                        .WithMany("BarRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailComment", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Cocktail", "Cocktail")
                        .WithMany("Comments")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.User", "User")
                        .WithMany("CocktailComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailIngredient", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Cocktail", "Cocktail")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.Ingredient", "Ingredient")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CocktailWizard.Data.Entities.CocktailRating", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Cocktail", "Cocktail")
                        .WithMany("Ratings")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.User", "User")
                        .WithMany("CocktailRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CocktailWizard.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CocktailWizard.Data.Entities.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
